print('===== EXERCÍCIO 004 ====')
print('Faça um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas as informações possíveis sobre ele.')
print('========================')
a = input('Informe algo:')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços?', a.isspace())
print('E um número?', a.isnumeric())
print('É um alfabético?', a.isalpha())
print('Esta em Minusculas?', a.isupper())