print('===== EXERCÍCIO 002 ====')
print('Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boas-vindas')
print('========================')
nome=input('Por favor, informe seu nome? ')
print('Olá, {}. Bem vindo ao segundo exercício de Python!'.format(nome))
print('^^^^^^^^^^^^^^^^^^^^^^^^')